name = "visitor-registration-api"
main = "index.js"
compatibility_date = "2024-01-01"

# 环境变量配置
[vars]
FEISHU_APP_ID = ""
FEISHU_APP_SECRET = ""
FEISHU_TABLE_TOKEN = ""
FEISHU_APP_TOKEN = ""

# 开发环境配置
[env.development]
vars = { ENVIRONMENT = "development" }

# 生产环境配置
[env.production]
vars = { ENVIRONMENT = "production" } 